name: celsius_vs_fahrenheit
description: THE Flame Game Jam 23 game
version: 0.1.0

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flame: ^1.12.0
  flame_audio: ^2.1.5
  flame_svg: ^1.8.7
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: 1.1.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: false

  assets:
    - assets/images/
    - assets/audio/
